server:
  port: 8090
spring:
  application:
    name: "employee"
  datasource:
    url: jdbc:h2:mem:testdb
    username: yj
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - employee-qa.yml
      - employee-prod.yml
  profiles:
    active: qa

management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 3.0.0

